parameters:
  asset.projects_collection.class: Walrus\Asset\AssetCollection
  yui_compressor.css.class: Assetic\Filter\Yui\CssCompressorFilter
  yui_compressor.js.class: Assetic\Filter\Yui\JsCompressorFilter
  walrus.group_assets: false

services:
  asset.projects_collection:
    class: %asset.projects_collection.class%
    arguments:
      - %walrus.group_assets%
    calls:
      - [ addFilter, [ css, @yui_compressor.css ]]
      - [ addFilter, [ js, @yui_compressor.js ]]

  yui_compressor.css:
    class: %yui_compressor.css.class%
    arguments:
      - %ROOT_PATH%/vendor/nervo/yuicompressor/yuicompressor.jar

  yui_compressor.js:
    class: %yui_compressor.js.class%
    arguments:
      - %ROOT_PATH%/vendor/nervo/yuicompressor/yuicompressor.jar