parameters:
  startup_project.command.class: Walrus\Command\StartupProjectCommand
  create_page.command.class: Walrus\Command\CreatePageCommand
  generate_site.command.class: Walrus\Command\GenerateSiteCommand
  startup_server.command.class: Walrus\Command\StartupServerCommand

services:
  create_page.command:
    class: %create_page.command.class%
    arguments:
      - @service_container

  generate_site.command:
    class: %generate_site.command.class%
    arguments:
      - @service_container

  startup_project.command:
    class: %startup_project.command.class%
    arguments:
      - @service_container

  startup_server.command:
    class: %startup_server.command.class%
    arguments:
      - @service_container
