parameters:
  startup_project.command.class: Walrus\Command\StartupProjectCommand
  create_page.command.class: Walrus\Command\CreatePageCommand
  generate_site.command.class: Walrus\Command\GenerateSiteCommand
  startup_server.command.class: Walrus\Command\StartupServerCommand

services:
  create_page.command:
    class: %create_page.command.class%
    arguments:
      #- @walrus.configuration
      #- @twig
      #- @utilities
      #- @walrus.collection.page
      - @service_container

  generate_site.command:
    class: %generate_site.command.class%
    arguments:
      #- @walrus.configuration
      #- @twig
      #- @twig.theme
      #- @twig.string
      #- @asset.projects_collection
      #- @walrus.collection.page
      - @service_container

  startup_project.command:
    class: %startup_project.command.class%
    arguments:
      - @walrus.configuration

  startup_server.command:
    class: %startup_server.command.class%
    arguments:
      - @walrus.configuration