parameters:
  create_page.command.class: Walrus\Command\CreatePageCommand
  generate_site.command.class: Walrus\Command\GenerateSiteCommand

services:
  create_page.command:
    class: %create_page.command.class%
    arguments:
      - @walrus.configuration
      - @twig
      - @utilities
      - @walrus.collection.page

  generate_site.command:
    class: %generate_site.command.class%
    arguments:
      - @walrus.configuration
      - @twig
      - @twig.theme
      - @twig.string
      - @asset.projects_collection
      - @walrus.collection.page