parameters:
  configuration.class: Walrus\DI\Configuration

services:
  walrus.configuration:
    class: %configuration.class%
    calls:
      - [ set, [ "root_dir", "%ROOT_PATH%" ]]
      - [ set, [ "drafing_dir", "%ROOT_PATH%/drafting" ]]
      - [ set, [ "public_dir", "%ROOT_PATH%/public" ]]