parameters:
  project.class: Walrus\Project\Project
  theme.class: Walrus\Theme\Theme

services:
  walrus.project:
    class: %project.class%
    arguments:
      - %ROOT_PATH%
      - @walrus.theme
    calls:
      - [ buildTheme ]

  walrus.theme:
    public: false
    class: %theme.class%
    arguments:
      - %THEME_PATH%
      - @asset.collection