parameters:
  twig.loader.class: Twig_Loader_Filesystem
  twig.loader.tpl_path: %ROOT_PATH%/Walrus/src/Walrus/Resources/tpl
  twig.loader.theme.tpl_path: %ROOT_PATH%/themes/cypress/templates
  twig.environment.class: Twig_Environment
  twig.cache: false
  twig.extension.walrus.class: Walrus\Twig\Extension\WalrusExtension

services:
  twig.loader:
    class: %twig.loader.class%
    arguments: [%twig.loader.tpl_path%]

  twig.loader.theme:
    class: %twig.loader.class%
    arguments: [%twig.loader.theme.tpl_path%]

  twig.extension.walrus:
    class: %twig.extension.walrus.class%
    arguments:
      - @walrus.configuration
      - @asset.projects_collection

  twig:
    class: %twig.environment.class%
    arguments:
      - @twig.loader
      - { cache: %twig.cache% }

  twig.theme:
    class: %twig.environment.class%
    arguments:
      - @twig.loader.theme
      - { cache: %twig.cache% }
    calls:
      - [ addExtension, [ @twig.extension.walrus ]]