parameters:
  twig.loader.class: Twig_Loader_Filesystem
  twig.loader.string.class: Twig_Loader_String
  twig.loader.tpl_path: %WALRUS_PATH%/src/Walrus/Resources/tpl
  twig.loader.theme.tpl_path: %WALRUS_PATH%/themes/cypress/templates
  twig.environment.class: Twig_Environment
  twig.cache: false
  twig.extension.theme.class: Walrus\Twig\Extension\ThemeExtension
  twig.extension.md_content.class: Walrus\Twig\Extension\MdContentExtension

services:
  twig.loader:
    class: %twig.loader.class%
    arguments: [%twig.loader.tpl_path%]

  twig:
    class: %twig.environment.class%
    arguments:
      - @twig.loader
      - { cache: %twig.cache% }

  twig.extension.md_content:
    class: %twig.extension.md_content.class%
    arguments:
      - @service_container

  twig.loader.md_content:
    class: %twig.loader.string.class%

  twig.md_content:
    class: %twig.environment.class%
    arguments:
      - @twig.loader.md_content
      - { cache: %twig.cache% }
    calls:
      - [ addExtension, [ @twig.extension.md_content ]]

  twig.extension.theme:
    class: %twig.extension.theme.class%
    arguments:
      - @service_container

  twig.loader.theme:
    class: %twig.loader.class%
    arguments: [%twig.loader.theme.tpl_path%]

  twig.theme:
    class: %twig.environment.class%
    arguments:
      - @twig.loader.theme
      - { cache: %twig.cache% }
    calls:
      - [ addExtension, [ @twig.extension.theme ]]