parameters:
  asset.collection.class: Walrus\Asset\AssetCollection
  uglify.css.class: Assetic\Filter\UglifyCssFilter
  uglify.js.class: Assetic\Filter\UglifyJsFilter

services:
  asset.collection:
    class: %asset.collection.class%
    arguments: ~
    calls:
      - [ addFilter, [ css, @uglify.css ]]
      - [ addFilter, [ js, @uglify.js ]]

  uglify.css:
    class: %uglify.css.class%
    arguments:
      - /usr/bin/uglifycss

  uglify.js:
    class: %uglify.js.class%
    arguments:
      - /usr/bin/uglifyjs